{% set version = "1.1.1" %}

package:
  name: s-tui
  version: {{ version }}

source:
  url: https://github.com/amanusk/s-tui/archive/v{{ version }}.tar.gz
  sha256: d999f40e7809b84b45c1c01aff76cf4fc37a058a92c6c8b80c1098941842d0de

build:
  number: 0
  # urwid not available for windows
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - urwid >=1.3.1
    - psutil >=5.2.0

test:
  imports:
    - s_tui

about:
  home: https://github.com/amanusk/s-tui
  license: GPL-2.0
  license_family: GPL
  license_file: LICENSE
  summary: Stress Terminal UI stress test and monitoring tool
  description: |
    s-tui is a terminal UI for monitoring your computer. s-tui allows to
    monitor CPU temperature, frequency, power and utilization in a graphical
    way from the terminal.
  doc_url: https://amanusk.github.io/s-tui
  dev_url: https://github.com/amanusk/s-tui

extra:
  recipe-maintainers:
    - ericdill
